---
title: "Health service use in the last two years of life"
author: "The Strategy Unit"
output:
  StrategyUnitTheme::su_document: default
params:
  stp: E54000033
  region_report: false
  include_forecasts: true
  include_costs: true
---

```{r setup, include=FALSE}

# NOTE: this Rmarkdown report generates a report that is close to the final published report. There are a number of
# figures, tables, text and charts that need to be manually inserted

library(knitr)
suppressMessages(
  library(cowplot, quietly = TRUE)
)
# knitr options ----
opts_chunk$set(echo = FALSE, eval.after = "fig.cap")

if (!knitr::is_latex_output()) {
  opts_chunk$set(dpi = 300,
                 dev.args = list(type = "cairo"))
}

# all setup should happen in setup.R that could be shared logic between files
invisible(local({
  source("setup.R")
  stp <- params$stp
  region_report <- params$region_report
  load_data(stp, region_report)
}))
```

```{r 3.2 numbers}
stp_deaths_18 <- nrow(mpi)
stp_deaths_20 <- forecast_deaths %>%
  filter(year == 2020, age_group >= 18) %>%
  pull(est_deaths) %>%
  sum()
stp_deaths_30 <- forecast_deaths %>%
  filter(year == 2030, age_group >= 18) %>%
  pull(est_deaths) %>%
  sum()
stp_deaths_pcnt <- (stp_deaths_30 / stp_deaths_18) - 1
```

```{r knit_child_docs, echo = FALSE, results = "asis"}
kc <- function(f) {
  e <- parent.frame()
  r <- knitr::knit_child(f, quiet = TRUE, envir = e)
  cat(r, sep = '\n')
}

kc("eol_01.Rmd")
kc("eol_02.Rmd")
if (params$include_forecasts) {
  kc("eol_03.Rmd")
}
kc("eol_04.Rmd")
kc("eol_05.Rmd")
kc("eol_06.Rmd")
kc("eol_07.Rmd")
if (params$include_costs) {
  kc("eol_08.Rmd")
}
kc("eol_09.Rmd")
```
