---
title: "End of Life - Pathways"
author: '[T. Jemmett](mailto:thomas.jemmett@nhs.net)'
date: "25/11/2019"
output:
  StrategyUnitTheme::su_document:
    toc: yes
  word_document:
    reference_docx: su_template.docx
    #toc: true
  html_document:
    fig_caption: true
    toc: true
    toc_float: true
params:
  stp: "E54000010"
  region_report: false
---

```{r setup, include=FALSE}
library(knitr)
library(magrittr)
# knitr options ----
opts_chunk$set(echo = FALSE, eval.after = "fig.cap")

if (!knitr::is_latex_output()) {
  opts_chunk$set(dpi = 300,
                 dev.args = list(type = "cairo"))
}

# all setup should happen in setup.R that could be shared logic between files
invisible(local({
  source("setup.R")
  load_data(params$stp, params$region_report)
}))
```

```{r create data, echo=FALSE, message=FALSE}
set.seed(234523)

pathway_data <- activity_region %>%
  inner_join(select(mpi_region, su_pat_id, group), by = "su_pat_id") %>%
  filter(group != "(Missing)",
         proximity_to_death_days < 365) %>%
  mutate_at("su_pat_id", as.character) %>%
  group_nest(group) %>%
  mutate_at("data", map, function(.x) {
    .x %>%
      group_by(su_pat_id) %>%
      mutate(n_act = sum(pod_type != "Bed")) %>%
      ungroup(su_pat_id) %>%
      mutate_at("n_act", ~.x %>%
                  quantile(c(0.15, 0.85)) %>%
                  set_names(c("left", "right")) %>%
                  c(.f = between) %>%
                  (lift_dv(partial)) %>%
                  {.(.x)}) %>%
      filter(n_act) %>%
      select(-n_act)
})

output_fn <- function(group, data) {
  cat("#", as.character(group), "\n")
  
  p <- data %>%
    filter(pod_summary_group != "Critical Care Bed Day") %>%
    mutate_at("pod_type",
              ~case_when(pod_summary_group == "Emergency Admission Bed Day" ~
                           "Urgent Bed Day",
                         pod_summary_group == "Elective Admission Bed Day" ~
                           "Planned Bed Day",
                         TRUE ~ as.character(.x)) %>%
                factor(levels = c("Urgent Service Event",
                                  "Urgent Bed Day",
                                  "Planned Admission",
                                  "Planned Bed Day",
                                  "Planned Contact"))) %>%
    mutate(order = !str_ends(pod_type, "Bed Day")) %>%
    arrange(order) %>%
    ggplot(aes(proximity_to_death_days, su_pat_id, fill = pod_type)) +
    # geom_tile(aes(height = ifelse(str_detect(pod_summary_group, "Bed Day"),
    #                               0.50,
    #                               0.75))) +
    geom_tile(height = 0.75) +
    scale_fill_manual(values = c(
      "Urgent Service Event" = "#EC6555",
      "Urgent Bed Day"       = "#F7C1BA",
      "Planned Admission"    = "#587FC1",
      "Planned Bed Day"      = "#BCCBE6",
      "Planned Contact"      = "#F8BF07"
    ), drop = FALSE) +
    scale_y_discrete(expand = expansion()) +
    scale_x_proximity_to_death_days(months_every = 3,
                                    expand = expansion(c(0.02, 0.001))) +
    theme(axis.text.y = element_blank(),
          axis.line.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.title = element_blank(),
          panel.border = element_blank(),
          panel.spacing = unit(0.1, "cm"),
          plot.margin = margin(0.1, 0.1, 0.1, 0.1, "cm"),
          legend.position = "bottom",
          legend.text = element_text(size = 9),
          legend.key.size = unit(.3, "cm")) +
    labs(x = "", y = "", fill = "")
  
  print(p)
  
  cat("\n\n")
}
```

```{r run output, echo=FALSE, message=FALSE, results='asis'}
N_SAMPLE <- 15

set.seed(234523)
pathway_data %>%
  # randomly sample the patients
  mutate_at("data", map, function(.x) {
    .x %>%
      nest(data = -su_pat_id) %>%
      sample_n(N_SAMPLE) %>%
      unnest(cols = c(data)) %>%
      ungroup()
  }) %>%
  pwalk(output_fn)
```
