---
title: "PCA of Activity"
author: '[Tom Jemmett](mailto:thomas.jemmett@nhs.net)'
date: "22/04/2020"
output: html_document
runtime: shiny
params:
  stp: "E54000015"
---

```{r setup, include=FALSE}
source("setup.R")
load_data(params$stp)

library(broom)
library(shiny)

knitr::opts_chunk$set(echo = TRUE)

```

```{r}
activity_summary <- inner_join(
  activity_region %>%
    group_by(su_pat_id) %>%
    # select(su_pat_id, proximity_to_death_days) %>%
    arrange(su_pat_id, desc(proximity_to_death_days)) %>%
    mutate(time_between = c(NA, -diff(proximity_to_death_days))) %>%
    summarise(#"Total Activity" = n(),
              "Earliest Activity" = max(proximity_to_death_days),
              "Average Time Between Activity" = mean(time_between, na.rm = TRUE)),

  activity_region %>%
    group_by(su_pat_id) %>%
    count(pod_summary_group) %>%
    pivot_wider(names_from = pod_summary_group, values_from = n) %>%
    mutate_at(vars(-su_pat_id), replace_na, 0),
  
  by = "su_pat_id"
) %>%
  inner_join(select(mpi_region, su_pat_id, age, imd_decile), by = "su_pat_id")

activity_matrix <- activity_summary %>%
  select(-su_pat_id) %>%
  replace_na(list(imd_decile = median(activity_summary$imd_decile, na.rm = TRUE),
                  "Average Time Between Activity" = 0)) %>%
  as.matrix()

rownames(activity_matrix) <- activity_summary$su_pat_id

activity_pca <- activity_matrix %>%
  prcomp(scale = TRUE)

pca_var <- tibble(PC = colnames(activity_pca$x),
                  var = activity_pca$sdev^2 / sum(activity_pca$sdev^2)) %>%
  mutate(cumvar = cumsum(var)) %>%
  mutate_at("PC", fct_inorder)
```

```{r}
ggplot(pca_var, aes(PC)) +
  geom_col(aes(y = var),
           colour = "dodgerblue",
           fill = after_scale(alpha("dodgerblue", 0.4))) +
  geom_line(aes(y = cumvar, group = ""), colour = after_scale(alpha("dodgerblue", 0.4))) +
  geom_point(aes(y = cumvar),
             colour = "dodgerblue") +
  scale_y_continuous(expand = expansion(c(0, 0.025)),
                     labels = percent) +
  labs(x = "",
       y = "% Variance Explained by Principle Component")
```

```{r}
pc_data <- activity_region %>%
  distinct(pod_type, pod_summary_group) %>%
  mutate_all(as.character) %>%
  right_join(suppressWarnings(
    tidy(activity_pca$rotation)
  ), by = c("pod_summary_group" = ".rownames")) %>%
  mutate_at("pod_type", replace_na, "Other") %>%
  pivot_longer(matches("PC\\d+"), names_to = "PC") %>%
  group_nest(PC) %>%
  mutate_at("PC", fct_relevel, levels(pca_var$PC)) %>%
  inner_join(pca_var, by = "PC") %>%
  arrange(PC)

selectInput("pc_choice", label = "Principle Components:",
            choices = pc_data$PC,
            selected = pc_data$PC[[1]])

renderPlot({
  pcf <- filter(pc_data, PC == input$pc_choice)
  
  data <- pcf$data[[1]]
  PC <- input$pc_choice
  var <- pcf$var[[1]]
  
  data %>%
    mutate_at("pod_summary_group", fct_reorder, quo(value)) %>%
    ggplot(aes(value, pod_summary_group, colour = pod_type)) +
    geom_col(aes(fill = after_scale(alpha(colour, 0.4)))) +
    labs(x = "",
         y = "",
         colour = "",
         title = glue("{PC}: var={percent(var)}")) +
    theme(axis.line = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 8),
          plot.background = element_rect(colour = "grey", fill = NA),
          plot.title = element_text(size = 9, margin = margin(2, 0, 0, 2)),
          plot.title.position = "plot",
          plot.margin = margin(),
          legend.position = "none")
})
```

