source("get_data/get_mpi.R", echo = TRUE)
source("get_data/get_activity.R", echo = TRUE)
source("get_data/get_activity_costs.R", echo = TRUE)
source("get_data/get_activity_ambulance.R", echo = TRUE)
source("get_data/get_forecast_deaths.R", echo = TRUE)
source("get_data/get_historic_deaths.R", echo = TRUE)
source("get_data/recreate_forecast_activity.R", echo = TRUE)
